server:
  port: 8081
  servlet:
    context-path: /api
    # cookie 过期时间
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: picFlow-backend
    # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/pic_flow?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    connect-timeout: 5000
  # session  配置
  session:
    store-type: redis
    # session 期时间
    timeout: 2592000
  profiles:
    active: local
  # 设置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
    # 仅在开发环境下打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
      logic-delete-field: is_delete #全局逻辑删除实体字段名
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.defen.picflowbackend.controller
# 对象存储配置（需要从腾讯云获取）
#cos:
#  client:
#    host:
#    secretId:
#    secretKey:
#    region:
#    bucket:
# 阿里云 AI 配置
#aliYunAi:
#  apiKey: